name: Run TCK with Server Side Filters

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 for TCK Executor
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Save JDK11 path
        run: |
          export JDK11_PATH=$JAVA_HOME
          echo "JDK11_PATH=$JDK11_PATH" >> $GITHUB_ENV
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with JDK11
        run: mvn -B clean install -DskipTests -Dspotbugs.skip=true

      - name: TCK tests - server side filters
        run: JAVA_HOME=$JDK11_PATH mvn -B verify -DskipTests -Prun-tck-server-side-filters
